(* Created with the Wolfram Language : www.wolfram.com *)
Dataset[{<|"colMasterM" -> "", "colControl" -> 
    DateObject[{2020, 5, 6, 0, 0, 0.}, "Instant", "Gregorian", -5.]|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "2020-06-29", 
   "colControl" -> DateObject[{2020, 5, 11, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> DateObject[{2020, 6, 9, 0, 0, 0.}, "Instant", "Gregorian", 
     -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> DateObject[{2020, 5, 8, 0, 0, 0.}, "Instant", "Gregorian", 
     -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> DateObject[{2020, 5, 29, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> DateObject[{2020, 5, 7, 0, 0, 0.}, 
     "Instant", "Gregorian", -5.]|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "2020-05-15", 
   "colControl" -> DateObject[{2020, 5, 3, 0, 0, 0.}, "Instant", "Gregorian", 
     -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "2020-06-02", 
   "colControl" -> DateObject[{2020, 5, 20, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "2020-05-25", 
   "colControl" -> DateObject[{2020, 5, 24, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> DateObject[{2020, 7, 24, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> DateObject[{2020, 5, 13, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "2020-06-10", "colControl" -> 
    DateObject[{2020, 6, 9, 0, 0, 0.}, "Instant", "Gregorian", -5.]|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> DateObject[{2020, 5, 20, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "2020-05-15", 
   "colControl" -> DateObject[{2020, 5, 14, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "2020-05-12", 
   "colControl" -> DateObject[{2020, 5, 11, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "2020-05-21", 
   "colControl" -> ""|>, <|"colMasterM" -> "2020-05-22", 
   "colControl" -> DateObject[{2020, 5, 16, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "2020-05-21", 
   "colControl" -> ""|>, <|"colMasterM" -> "2020-05-13", 
   "colControl" -> DateObject[{2020, 5, 6, 0, 0, 0.}, "Instant", "Gregorian", 
     -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "2020-05-22", "colControl" -> 
    DateObject[{2020, 5, 8, 0, 0, 0.}, "Instant", "Gregorian", -5.]|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> DateObject[{2020, 5, 11, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> DateObject[{2020, 5, 7, 0, 0, 0.}, 
     "Instant", "Gregorian", -5.]|>, <|"colMasterM" -> "2020-05-22", 
   "colControl" -> DateObject[{2020, 4, 29, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> DateObject[{2020, 5, 1, 0, 0, 0.}, 
     "Instant", "Gregorian", -5.]|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> DateObject[{2020, 5, 2, 0, 0, 0.}, "Instant", "Gregorian", 
     -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "2020-05-16", "colControl" -> 
    DateObject[{2020, 5, 15, 0, 0, 0.}, "Instant", "Gregorian", -5.]|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "2020-05-15", 
   "colControl" -> DateObject[{2020, 5, 11, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "2020-06-10", 
   "colControl" -> DateObject[{2020, 6, 7, 0, 0, 0.}, "Instant", "Gregorian", 
     -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> DateObject[{2020, 5, 5, 0, 0, 0.}, "Instant", "Gregorian", 
     -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "2020-05-22", 
   "colControl" -> DateObject[{2020, 5, 7, 0, 0, 0.}, "Instant", "Gregorian", 
     -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "2020-05-25", 
   "colControl" -> DateObject[{2020, 5, 24, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "2020-05-21", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> DateObject[{2020, 5, 6, 0, 0, 0.}, 
     "Instant", "Gregorian", -5.]|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> DateObject[{2020, 5, 13, 0, 0, 0.}, 
     "Instant", "Gregorian", -5.]|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> DateObject[{2020, 5, 7, 0, 0, 0.}, 
     "Instant", "Gregorian", -5.]|>, <|"colMasterM" -> "", 
   "colControl" -> DateObject[{2020, 5, 18, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> DateObject[{2020, 5, 2, 0, 0, 0.}, "Instant", "Gregorian", 
     -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> DateObject[{2020, 5, 4, 0, 0, 0.}, "Instant", "Gregorian", 
     -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> DateObject[{2020, 5, 18, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "2020-06-05", 
   "colControl" -> DateObject[{2020, 5, 4, 0, 0, 0.}, "Instant", "Gregorian", 
     -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "2020-05-11", 
   "colControl" -> DateObject[{2020, 5, 5, 0, 0, 0.}, "Instant", "Gregorian", 
     -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> DateObject[{2020, 5, 17, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "2020-05-19", 
   "colControl" -> DateObject[{2020, 5, 12, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "2020-05-28", "colControl" -> 
    DateObject[{2020, 5, 10, 0, 0, 0.}, "Instant", "Gregorian", -5.]|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "2020-06-02", 
   "colControl" -> DateObject[{2020, 5, 30, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> DateObject[{2020, 5, 10, 0, 0, 0.}, 
     "Instant", "Gregorian", -5.]|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "2020-06-21", "colControl" -> 
    DateObject[{2020, 5, 5, 0, 0, 0.}, "Instant", "Gregorian", -5.]|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "2020-05-15", 
   "colControl" -> DateObject[{2020, 5, 8, 0, 0, 0.}, "Instant", "Gregorian", 
     -5.]|>, <|"colMasterM" -> "2020-05-21", "colControl" -> ""|>, 
  <|"colMasterM" -> "2020-05-15", "colControl" -> 
    DateObject[{2020, 5, 14, 0, 0, 0.}, "Instant", "Gregorian", -5.]|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "2020-05-11", "colControl" -> 
    DateObject[{2020, 5, 11, 0, 0, 0.}, "Instant", "Gregorian", -5.]|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> DateObject[{2020, 5, 12, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> DateObject[{2020, 7, 24, 0, 0, 0.}, "Instant", 
     "Gregorian", -5.]|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "2020-05-13", "colControl" -> 
    DateObject[{2020, 5, 10, 0, 0, 0.}, "Instant", "Gregorian", -5.]|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>, <|"colMasterM" -> "", "colControl" -> ""|>, 
  <|"colMasterM" -> "", "colControl" -> ""|>, <|"colMasterM" -> "", 
   "colControl" -> ""|>}, TypeSystem`Vector[
  TypeSystem`Struct[{"colMasterM", "colControl"}, 
   {TypeSystem`Atom[String], TypeSystem`AnyType}], 1001], <||>]
